set(CMAKE_CXX_STANDARD 20 CACHE STRING "" FORCE)
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE STRING "" FORCE)
set(CMAKE_CXX_EXTENSIONS OFF CACHE STRING "" FORCE)

set(MSVC_COMMON "/nologo /W3 /DWIN32 /D_WINDOWS /FC /MP /Zc:inline /wd28251 /wd26451 /utf-8")
set(MSVC_COMMON_DEBUG "/MTd /Ob0 /Od /RTC1 /GS /ZI /D_DEBUG")
set(MSVC_COMMON_RELEASE "/MT /Ox /Os /Oi /GF /Gy /GS- /GL /Z7 /DNDEBUG")

set(CMAKE_C_FLAGS "${MSVC_COMMON}" CACHE STRING "")
#set(CMAKE_CXX_FLAGS "${MSVC_COMMON} /EHsc /d2FH4 /GR- /Zc:__cplusplus /permissive- /await" CACHE STRING "")
set(CMAKE_CXX_FLAGS "${MSVC_COMMON} /EHs-c- /GR- /D_HAS_EXCEPTIONS=0 /Zc:__cplusplus /permissive- /await" CACHE STRING "")

set(CMAKE_C_FLAGS_DEBUG "${MSVC_COMMON_DEBUG}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG "${MSVC_COMMON_DEBUG}" CACHE STRING "")

set(CMAKE_C_FLAGS_RELEASE "${MSVC_COMMON_RELEASE}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE "${MSVC_COMMON_RELEASE} /await:heapelide" CACHE STRING "")

set(CMAKE_STATIC_LINKER_FLAGS_DEBUG "" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "/DEBUG:FASTLINK /INCREMENTAL" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG "/DEBUG:FASTLINK /INCREMENTAL" CACHE STRING "")

set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "/INCREMENTAL:NO /LTCG:INCREMENTAL" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "/DEBUG:FULL /INCREMENTAL:NO /OPT:REF /OPT:ICF /LTCG:INCREMENTAL" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/DEBUG:FULL /INCREMENTAL:NO /OPT:REF /OPT:ICF /LTCG:INCREMENTAL" CACHE STRING "")

set(CMAKE_RC_FLAGS "/nologo -c65001 /DWIN32" CACHE STRING "")
